[package]
name = "axiom-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
axiom-core = { workspace = true }
axiom-syntax = { workspace = true }
axiom-ir = { workspace = true }
axiom-jit = { workspace = true, features = ["native-jit"] }
axiom-sim = { workspace = true }
axiom-telemetry = { workspace = true }
axiom-desktop = { workspace = true }
axiom-lsp = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tiny_http = { workspace = true }
zstd = { workspace = true }

[build-dependencies]
zstd = { workspace = true }

[[bin]]
name = "axiom"
path = "src/main.rs"
