[package]
name = "betterado-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
betterado-core = { workspace = true }
betterado-syntax = { workspace = true }
betterado-ir = { workspace = true }
betterado-jit = { workspace = true }
betterado-sim = { workspace = true }
betterado-telemetry = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[[bin]]
name = "axiom"
path = "src/main.rs"
