// Axiom EDA — Unified Power-Performance-Area (PPA) Evaluator & Silicon Cost Forecaster
// Provides concurrent evaluation of Area, Performance, Power, FPGA fitting margins, and ASIC PDK die area.

use axiom_ir::{BirCircuit, PrimitiveKind};
use axiom_sta::{analyze_circuit, SlackRadarSummary, StaOptions};
use serde::{Deserialize, Serialize};

/// Comprehensive Power-Performance-Area (PPA) Metrics.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PpaMetrics {
    // --- Area Metrics ---
    pub lut_count: u64,
    pub ff_count: u64,
    pub bram_36k_count: u32,
    pub bram_18k_count: u32,
    pub dsp_slice_count: u32,
    pub total_equivalent_logic_cells: u64,
    pub asic_gate_count: u64,
    pub asic_core_area_um2: f64,
    pub asic_die_area_mm2: f64,

    // --- Performance Metrics ---
    pub fmax_mhz: f32,
    pub clock_period_ps: f32,
    pub critical_path_delay_ps: f32,
    pub worst_negative_slack_ps: f32,
    pub total_negative_slack_ps: f32,
    pub logic_depth: u32,
    pub latency_cycles: u32,

    // --- Power Metrics ---
    pub dynamic_power_mw: f32,
    pub static_power_mw: f32,
    pub total_power_mw: f32,
    pub energy_per_cycle_pj: f32,
    pub junction_temperature_c: f32,

    // --- Figure of Merit ---
    pub fom_score: f32,
}

/// Physical resource capacity and commercial specs of an FPGA target device.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FpgaDeviceProfile {
    pub id: String,
    pub name: String,
    pub family: String,
    pub lut_capacity: u64,
    pub ff_capacity: u64,
    pub bram_capacity: u32,
    pub dsp_capacity: u32,
    pub io_pin_count: u32,
    pub speed_grade: String,
    pub reference_cost_usd: f32,
}

/// Device fitting status.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum FpgaFitStatus {
    Fits,
    ExceedsCapacity,
}

/// Detailed fitting analysis of a circuit on a candidate FPGA device.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FpgaFitEvaluation {
    pub profile: FpgaDeviceProfile,
    pub status: FpgaFitStatus,
    pub lut_utilization_pct: f32,
    pub ff_utilization_pct: f32,
    pub bram_utilization_pct: f32,
    pub dsp_utilization_pct: f32,
    pub max_utilization_pct: f32,
    pub bottleneck_resource: String,
    pub estimated_cost_usd: f32,
    pub cost_delta_vs_target: f32,
    pub is_current_target: bool,
    pub is_recommended: bool,
}

/// Open-source ASIC PDK technology options.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AsicPdk {
    SkyWater130,
    IhpSg13g2,
}

/// Silicon die area and GDSII fabrication cost forecast for open-source ASIC PDKs.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AsicForecast {
    pub pdk_name: String,
    pub technology_node_nm: u32,
    pub gate_count: u64,
    pub core_area_um2: f64,
    pub routing_overhead_factor: f32,
    pub die_area_mm2: f64,
    pub die_width_mm: f32,
    pub die_height_mm: f32,
    pub pad_ring_io_count: u32,
    pub estimated_mpw_shuttle_cost_usd: f32,
    pub estimated_mask_set_cost_usd: f32,
}

/// Single point along the Power-Performance-Area Pareto frontier curve.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ParetoPoint {
    pub freq_mhz: f32,
    pub power_mw: f32,
    pub energy_pj: f32,
    pub area_score: f32,
    pub slack_ps: f32,
    pub fom: f32,
}

/// Configuration options for PPA evaluation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PpaOptions {
    pub target_device: Option<String>,
    pub target_clock_freq_mhz: Option<f32>,
    pub junction_temp_c: Option<f32>,
    pub core_voltage_v: Option<f32>,
    pub switching_activity_alpha: Option<f32>,
    pub pdk: Option<String>,
}

impl Default for PpaOptions {
    fn default() -> Self {
        Self {
            target_device: Some("xcku5p-ffvb676-2-e".to_string()),
            target_clock_freq_mhz: Some(100.0),
            junction_temp_c: Some(25.0),
            core_voltage_v: Some(0.95),
            switching_activity_alpha: Some(0.125),
            pdk: Some("sky130".to_string()),
        }
    }
}

/// Complete report generated by the PPA Evaluator.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PpaReport {
    pub top_module: String,
    pub metrics: PpaMetrics,
    pub fpga_evaluations: Vec<FpgaFitEvaluation>,
    pub recommended_device_id: Option<String>,
    pub asic_forecast: AsicForecast,
    pub pareto_curve: Vec<ParetoPoint>,
    pub optimization_suggestions: Vec<String>,
}

/// Evaluator engine for live Power-Performance-Area analysis.
pub struct PpaEvaluator;

impl PpaEvaluator {
    /// Returns the standard FPGA device profiles for multi-target silicon comparison.
    pub fn standard_fpga_catalog() -> Vec<FpgaDeviceProfile> {
        vec![
            FpgaDeviceProfile {
                id: "xc7a100tcsg324-1".to_string(),
                name: "Artix-7 XC7A100T".to_string(),
                family: "Artix-7".to_string(),
                lut_capacity: 63_400,
                ff_capacity: 126_800,
                bram_capacity: 135,
                dsp_capacity: 240,
                io_pin_count: 210,
                speed_grade: "-1".to_string(),
                reference_cost_usd: 85.00,
            },
            FpgaDeviceProfile {
                id: "xc7z020clg484-1".to_string(),
                name: "Zynq-7000 XC7Z020".to_string(),
                family: "Zynq-7000".to_string(),
                lut_capacity: 53_200,
                ff_capacity: 106_400,
                bram_capacity: 140,
                dsp_capacity: 220,
                io_pin_count: 200,
                speed_grade: "-1".to_string(),
                reference_cost_usd: 95.00,
            },
            FpgaDeviceProfile {
                id: "xc7k325tffg900-2".to_string(),
                name: "Kintex-7 XC7K325T".to_string(),
                family: "Kintex-7".to_string(),
                lut_capacity: 203_800,
                ff_capacity: 407_600,
                bram_capacity: 445,
                dsp_capacity: 840,
                io_pin_count: 500,
                speed_grade: "-2".to_string(),
                reference_cost_usd: 450.00,
            },
            FpgaDeviceProfile {
                id: "xc7vx415tffg1158-1".to_string(),
                name: "Virtex-7 XC7VX415T".to_string(),
                family: "Virtex-7".to_string(),
                lut_capacity: 257_600,
                ff_capacity: 515_200,
                bram_capacity: 880,
                dsp_capacity: 2_160,
                io_pin_count: 350,
                speed_grade: "-1".to_string(),
                reference_cost_usd: 1200.00,
            },
            FpgaDeviceProfile {
                id: "xcku5p-ffvb676-2-e".to_string(),
                name: "Kintex UltraScale+ XCKU5P".to_string(),
                family: "Kintex UltraScale+".to_string(),
                lut_capacity: 216_960,
                ff_capacity: 433_920,
                bram_capacity: 480,
                dsp_capacity: 1_824,
                io_pin_count: 400,
                speed_grade: "-2".to_string(),
                reference_cost_usd: 650.00,
            },
            FpgaDeviceProfile {
                id: "xcvu9p-flga2104-2-e".to_string(),
                name: "Virtex UltraScale+ XCVU9P".to_string(),
                family: "Virtex UltraScale+".to_string(),
                lut_capacity: 1_182_240,
                ff_capacity: 2_364_480,
                bram_capacity: 2_160,
                dsp_capacity: 6_840,
                io_pin_count: 832,
                speed_grade: "-2".to_string(),
                reference_cost_usd: 4800.00,
            },
        ]
    }

    /// Evaluates the Power, Performance, and Area of a compiled BIR circuit.
    pub fn evaluate(
        circuit: &BirCircuit,
        sta_summary: Option<&SlackRadarSummary>,
        options: Option<PpaOptions>,
    ) -> PpaReport {
        let opts = options.unwrap_or_default();
        let target_dev_id = opts.target_device.as_deref().unwrap_or("xcku5p-ffvb676-2-e");
        let junction_temp = opts.junction_temp_c.unwrap_or(25.0);
        let vdd = opts.core_voltage_v.unwrap_or(0.95);
        let alpha = opts.switching_activity_alpha.unwrap_or(0.125);

        // 1. Hardware Resource Estimation
        let mut lut_count: u64 = 0;
        let mut ff_count: u64 = 0;
        let mut bram_36k_count: u32 = 0;
        let mut bram_18k_count: u32 = 0;
        let mut dsp_slice_count: u32 = 0;

        // Count from continuous assigns and processes
        lut_count += circuit.continuous_assigns.len() as u64;

        for proc in &circuit.processes {
            match proc.kind {
                axiom_ir::BirProcessKind::Clocked => {
                    for stmt in &proc.body {
                        if let axiom_ir::BirStatement::Assign { target, .. } = stmt {
                            let width = circuit.nets.get(target.0 as usize).map(|n| n.width as u64).unwrap_or(1);
                            ff_count += width.max(1);
                        }
                    }
                }
                axiom_ir::BirProcessKind::Combinational => {
                    lut_count += proc.body.len() as u64;
                }
                _ => {}
            }
        }

        // Count primitives (RAMB, DSP, LUT, FDRE)
        for prim in &circuit.primitive_instances {
            match prim.primitive_kind {
                PrimitiveKind::Lut6 | PrimitiveKind::Lut6_2 | PrimitiveKind::Lut5 | PrimitiveKind::Lut4 | PrimitiveKind::Lut3 | PrimitiveKind::Lut2 | PrimitiveKind::Lut1 => {
                    lut_count += 1;
                }
                PrimitiveKind::Fdre | PrimitiveKind::Fdse | PrimitiveKind::Fdce | PrimitiveKind::Fdpe => {
                    ff_count += 1;
                }
                PrimitiveKind::Dsp48e2 | PrimitiveKind::Dsp48e1 => {
                    dsp_slice_count += 1;
                }
                PrimitiveKind::Ramb36e2 => {
                    bram_36k_count += 1;
                }
                PrimitiveKind::Ramb18e2 => {
                    bram_18k_count += 1;
                }
                _ => {}
            }
        }

        // Minimum floor of 1 for non-empty designs
        lut_count = lut_count.max(1);
        ff_count = ff_count.max(1);

        let total_equiv_cells = lut_count + ff_count + (bram_36k_count as u64 * 360) + (dsp_slice_count as u64 * 120);

        // 2. Performance Metrics
        let (fmax_mhz, clock_period_ps, crit_delay_ps, wns_ps, tns_ps, logic_depth) = if let Some(sta) = sta_summary {
            (
                sta.fmax_mhz,
                sta.clock_period_ps,
                sta.critical_path.data_delay_ps,
                sta.worst_negative_slack_ps,
                sta.total_negative_slack_ps,
                sta.critical_path.logic_levels,
            )
        } else {
            let sta = analyze_circuit(circuit, "", Some(StaOptions {
                target_device: target_dev_id.to_string(),
                ..Default::default()
            }));
            (
                sta.fmax_mhz,
                sta.clock_period_ps,
                sta.critical_path.data_delay_ps,
                sta.worst_negative_slack_ps,
                sta.total_negative_slack_ps,
                sta.critical_path.logic_levels,
            )
        };

        let target_freq = opts.target_clock_freq_mhz.unwrap_or_else(|| fmax_mhz.min(250.0));
        let latency_cycles = 1 + logic_depth / 4;

        // 3. Silicon Power Evaluation (Physics-based)
        let total_net_cap_pf = (circuit.nets.len() as f32 * 0.035).max(0.5);
        let dynamic_power_mw = 0.5 * (total_net_cap_pf * 1e-12) * (vdd * vdd) * (target_freq * 1e6) * alpha * 1000.0 * (lut_count as f32).sqrt().max(1.0);

        let base_static_mw = 18.5 + (total_equiv_cells as f32 * 0.002);
        let temp_factor = 2.0_f32.powf((junction_temp - 25.0) / 15.0);
        let static_power_mw = base_static_mw * temp_factor * (vdd / 0.95);

        let total_power_mw = dynamic_power_mw + static_power_mw;
        let energy_per_cycle_pj = if target_freq > 0.0 {
            (total_power_mw * 1e-3) / (target_freq * 1e6) * 1e12
        } else {
            0.0
        };

        // 4. ASIC Standard Cell Model
        let asic_pdk = match opts.pdk.as_deref() {
            Some("ihp") | Some("ihp_sg13g2") => AsicPdk::IhpSg13g2,
            _ => AsicPdk::SkyWater130,
        };

        let asic_gate_count = (lut_count * 5)
            + (ff_count * 8)
            + (dsp_slice_count as u64 * 1500)
            + (bram_36k_count as u64 * 48_000)
            + (bram_18k_count as u64 * 24_000);

        let (gate_area_um2, pdk_name, tech_nm, mpw_cost, mask_cost) = match asic_pdk {
            AsicPdk::SkyWater130 => (10.8, "SkyWater 130nm (sky130_fd_sc_hd)", 130, 9750.0, 185_000.0),
            AsicPdk::IhpSg13g2 => (9.6, "IHP SG13G2 (0.13um BiCMOS)", 130, 18500.0, 240_000.0),
        };

        let routing_overhead = 1.40_f32;
        let asic_core_area_um2 = (asic_gate_count as f64 * gate_area_um2) * (routing_overhead as f64);
        let asic_core_area_mm2 = asic_core_area_um2 / 1_000_000.0;

        let core_dim_mm = asic_core_area_mm2.sqrt() as f32;
        let die_width_mm = (core_dim_mm + 0.30).max(1.0);
        let die_height_mm = (core_dim_mm + 0.30).max(1.0);
        let asic_die_area_mm2 = (die_width_mm * die_height_mm) as f64;

        let pad_ring_io_count = ((die_width_mm + die_height_mm) * 2.0 * 8.0) as u32;

        let asic_forecast = AsicForecast {
            pdk_name: pdk_name.to_string(),
            technology_node_nm: tech_nm,
            gate_count: asic_gate_count,
            core_area_um2: asic_core_area_um2,
            routing_overhead_factor: routing_overhead,
            die_area_mm2: asic_die_area_mm2,
            die_width_mm,
            die_height_mm,
            pad_ring_io_count,
            estimated_mpw_shuttle_cost_usd: mpw_cost,
            estimated_mask_set_cost_usd: mask_cost,
        };

        // 5. Figure of Merit (FoM): Frequency / (Power_W * NormArea)
        let power_w = (total_power_mw * 1e-3).max(0.001);
        let norm_area = (total_equiv_cells as f32 / 1000.0).max(0.1);
        let fom_score = fmax_mhz / (power_w * norm_area);

        let metrics = PpaMetrics {
            lut_count,
            ff_count,
            bram_36k_count,
            bram_18k_count,
            dsp_slice_count,
            total_equivalent_logic_cells: total_equiv_cells,
            asic_gate_count,
            asic_core_area_um2,
            asic_die_area_mm2,
            fmax_mhz,
            clock_period_ps,
            critical_path_delay_ps: crit_delay_ps,
            worst_negative_slack_ps: wns_ps,
            total_negative_slack_ps: tns_ps,
            logic_depth,
            latency_cycles,
            dynamic_power_mw,
            static_power_mw,
            total_power_mw,
            energy_per_cycle_pj,
            junction_temperature_c: junction_temp,
            fom_score,
        };

        // 6. Multi-Target FPGA Device Fitting Analysis
        let catalog = Self::standard_fpga_catalog();
        let target_cost = catalog
            .iter()
            .find(|p| p.id == target_dev_id)
            .map(|p| p.reference_cost_usd)
            .unwrap_or(650.0);

        let mut evaluations = Vec::new();
        let mut recommended_id: Option<String> = None;
        let mut min_fitting_cost = f32::MAX;

        for profile in catalog {
            let lut_pct = (lut_count as f32 / profile.lut_capacity as f32) * 100.0;
            let ff_pct = (ff_count as f32 / profile.ff_capacity as f32) * 100.0;
            let bram_pct = if profile.bram_capacity > 0 {
                ((bram_36k_count * 2 + bram_18k_count) as f32 / (profile.bram_capacity * 2) as f32) * 100.0
            } else {
                0.0
            };
            let dsp_pct = if profile.dsp_capacity > 0 {
                (dsp_slice_count as f32 / profile.dsp_capacity as f32) * 100.0
            } else {
                0.0
            };

            let max_pct = lut_pct.max(ff_pct).max(bram_pct).max(dsp_pct);
            let fits = max_pct <= 100.0;

            let bottleneck = if max_pct == lut_pct {
                "LUT Logic".to_string()
            } else if max_pct == ff_pct {
                "Flip-Flops".to_string()
            } else if max_pct == bram_pct {
                "Block RAM".to_string()
            } else {
                "DSP Slices".to_string()
            };

            let is_current = profile.id == target_dev_id;
            let cost_delta = profile.reference_cost_usd - target_cost;

            if fits && profile.reference_cost_usd < min_fitting_cost {
                min_fitting_cost = profile.reference_cost_usd;
                recommended_id = Some(profile.id.clone());
            }

            evaluations.push(FpgaFitEvaluation {
                profile,
                status: if fits { FpgaFitStatus::Fits } else { FpgaFitStatus::ExceedsCapacity },
                lut_utilization_pct: lut_pct,
                ff_utilization_pct: ff_pct,
                bram_utilization_pct: bram_pct,
                dsp_utilization_pct: dsp_pct,
                max_utilization_pct: max_pct,
                bottleneck_resource: bottleneck,
                estimated_cost_usd: 0.0,
                cost_delta_vs_target: cost_delta,
                is_current_target: is_current,
                is_recommended: false,
            });
        }

        for eval in &mut evaluations {
            eval.estimated_cost_usd = eval.profile.reference_cost_usd;
            if Some(&eval.profile.id) == recommended_id.as_ref() {
                eval.is_recommended = true;
            }
        }

        // 7. Generate Pareto Frontier Curve (Sweep Frequency vs Power vs Slack)
        let mut pareto_curve = Vec::new();
        let sweep_steps = 11;
        let base_fmax = fmax_mhz.max(20.0);
        let min_f = (base_fmax * 0.4).max(10.0);
        let max_f = base_fmax * 1.6;
        let step_f = (max_f - min_f) / ((sweep_steps - 1) as f32);

        for step in 0..sweep_steps {
            let f = min_f + step_f * (step as f32);
            let dyn_p = 0.5 * (total_net_cap_pf * 1e-12) * (vdd * vdd) * (f * 1e6) * alpha * 1000.0 * (lut_count as f32).sqrt().max(1.0);
            let tot_p = dyn_p + static_power_mw;
            let cycle_energy = (tot_p * 1e-3) / (f * 1e6) * 1e12;

            let period_ps = 1_000_000.0 / f;
            let slack = period_ps - crit_delay_ps;
            let fom = f / ((tot_p * 1e-3).max(0.001) * norm_area);

            pareto_curve.push(ParetoPoint {
                freq_mhz: f,
                power_mw: tot_p,
                energy_pj: cycle_energy,
                area_score: norm_area,
                slack_ps: slack,
                fom,
            });
        }

        // 8. Design Optimization Suggestions
        let mut suggestions = Vec::new();
        if wns_ps < 0.0 {
            suggestions.push(format!(
                "Timing violation detected (WNS: {:.1} ps). Use Silicon Copilot auto-pipelining to improve Fmax by ~50-100%.",
                wns_ps
            ));
        }
        if let Some(ref rec_id) = recommended_id {
            if rec_id != target_dev_id {
                if let Some(rec) = evaluations.iter().find(|e| &e.profile.id == rec_id) {
                    if rec.cost_delta_vs_target < 0.0 {
                        suggestions.push(format!(
                            "BOM Cost Savings: Circuit fits comfortably on '{}' saving ${:.2} per unit ({:.1}% max utilization).",
                            rec.profile.name,
                            rec.cost_delta_vs_target.abs(),
                            rec.max_utilization_pct
                        ));
                    }
                }
            }
        }
        if static_power_mw > dynamic_power_mw * 1.5 {
            suggestions.push("Static leakage dominates active power. Consider lowering core supply voltage or applying sleep gating to unused logic.".to_string());
        }
        if logic_depth > 12 {
            suggestions.push(format!(
                "Deep combinational logic cone (depth: {} levels). Slicing into 2 pipeline stages will significantly reduce dynamic power per clock edge.",
                logic_depth
            ));
        }

        PpaReport {
            top_module: circuit.top_name.clone(),
            metrics,
            fpga_evaluations: evaluations,
            recommended_device_id: recommended_id,
            asic_forecast,
            pareto_curve,
            optimization_suggestions: suggestions,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use axiom_core::LogicVector;
    use axiom_ir::{BirCircuit, BirContinuousAssign, BirExpr};
    use axiom_syntax::BinaryOp;

    #[test]
    fn test_ppa_evaluation_simple_circuit() {
        let mut circuit = BirCircuit::new("alu_ppa");
        let a = circuit.add_net("a", 16, LogicVector::from_u64(0, 16));
        let b = circuit.add_net("b", 16, LogicVector::from_u64(0, 16));
        let out = circuit.add_net("out", 16, LogicVector::from_u64(0, 16));

        circuit.continuous_assigns.push(BirContinuousAssign {
            target: out,
            expr: BirExpr::Binary {
                op: BinaryOp::Add,
                lhs: Box::new(BirExpr::Net(a)),
                rhs: Box::new(BirExpr::Net(b)),
            },
        });

        let report = PpaEvaluator::evaluate(&circuit, None, None);

        assert_eq!(report.top_module, "alu_ppa");
        assert!(report.metrics.fmax_mhz > 0.0);
        assert!(report.metrics.total_power_mw > 0.0);
        assert!(report.metrics.asic_die_area_mm2 > 0.0);
        assert_eq!(report.fpga_evaluations.len(), 6);
        assert_eq!(report.pareto_curve.len(), 11);
        assert!(report.recommended_device_id.is_some());
    }

    #[test]
    fn test_fpga_device_fitting_recommendation() {
        let circuit = BirCircuit::new("small_circuit");
        let report = PpaEvaluator::evaluate(&circuit, None, None);

        let artix = report.fpga_evaluations.iter().find(|e| e.profile.family == "Artix-7").unwrap();
        assert_eq!(artix.status, FpgaFitStatus::Fits);
        assert!(report.recommended_device_id.unwrap().contains("xc7a100t"));
    }
}
