[package]
name = "betterado-desktop"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
betterado-core = { workspace = true }
betterado-syntax = { workspace = true }
betterado-ir = { workspace = true }
betterado-jit = { workspace = true }
betterado-sim = { workspace = true }
betterado-telemetry = { workspace = true }
serde = { workspace = true }
serde_json = "1.0"
thiserror = { workspace = true }
hashbrown = { workspace = true }
