[package]
name = "axiom-syntax"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
axiom-core.workspace = true
thiserror.workspace = true
serde.workspace = true
lasso.workspace = true
bumpalo.workspace = true
smallvec.workspace = true
